Repository Inner-Worlds/inner-worlds-ui, pull requests merged in 2023-05, with the labels that each got.

#30 Add routes to the App component
  src/Components/App/App.js
  src/Components/DreamInput/DreamInput.js
  src/Components/DreamList/DreamList.js
  src/Components/Header/Header.css
  src/Components/Header/Header.js
  src/Components/Login/Login.js
  src/Components/NotFound/NotFound.js
Labels: FE

#33 Setup/nav bar
  src/Components/App/App.js
  src/Components/DreamList/DreamList.js
  src/Components/Nav/Nav.css
  src/Components/Nav/Nav.js
  src/mock-data.js
Labels: enhancement, FE, Iteration 1, Styling

#48 add responsive styling
  src/Components/DreamInput/DreamInput.css
  src/Components/Login/Login.css
  src/Components/Nav/Nav.css
  src/Components/Nav/Nav.js
Labels: enhancement, FE, Iteration 1, Styling

#67 Style/edit dream
  src/Components/App/App.css
  src/Components/App/App.js
  src/Components/DreamCard/DreamCard.css
  src/Components/DreamCard/DreamCard.js
  src/Components/DreamInput/DreamInput.js
  src/Components/DreamList/DreamList.css
  src/Components/DreamList/DreamList.js
  src/Components/Nav/Nav.js
  src/mock-data.js
  src/options.js
  src/queries.js
Labels: bug, enhancement, FE

#64 Feat/error handling
  src/Components/App/App.css
  src/Components/App/App.js
  src/Components/DreamCard/DreamCard.css
  src/Components/DreamCard/DreamCard.js
  src/Components/DreamInput/DreamInput.css
  src/Components/DreamInput/DreamInput.js
  src/Components/DreamList/DreamList.js
  src/Components/Login/Login.css
  src/Components/Login/Login.js
Labels: FE, Iteration 3

#59 Feat/cypress
  .github/workflows/fe-ci.yml
  cypress/e2e/Dreams.cy.js
  cypress/e2e/Home.cy.js
  cypress/e2e/Login.cy.js
  cypress/e2e/spec.cy.js
  cypress/fixtures/defaultEmotions.json
  cypress/fixtures/defaultTags.json
  cypress/fixtures/deletedDream.json
  cypress/fixtures/dreamFixture.json
  cypress/fixtures/errorFixture.json
  cypress/fixtures/example.json
  cypress/fixtures/updatedDream.json
  cypress/fixtures/userFixture.json
  cypress/support/commands.js
  cypress/support/e2e.js
  src/Components/App/App.js
  src/mock-data.js
  src/options.js
Labels: FE, Iteration 1, Testing

#72 Feat/dream stats
  cypress/e2e/Login.cy.js
  cypress/fixtures/userFixture.json
  package-lock.json
  package.json
  src/Components/App/App.js
  src/Components/DreamCard/DreamCard.css
  src/Components/DreamCard/DreamCard.js
  src/Components/DreamChart/DreamChart.css
  src/Components/DreamChart/DreamChart.js
  src/Components/DreamInput/DreamInput.js
  src/Components/Login/Login.js
  src/Components/Nav/Nav.css
  src/Components/Nav/Nav.js
  src/DreamData.js
  src/queries.js
Labels: enhancement, FE, Iteration 3

#73 Feat/accessibility
  src/Components/DreamCard/DreamCard.js
  src/Components/DreamInput/DreamInput.css
  src/Components/DreamInput/DreamInput.js
Labels: FE, Iteration 3
